import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastProvider from "./(Frontend)/components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white min-h-screen flex items-center justify-center">
        <div className="relative w-[375px] min-h-screen bg-gray-50 shadow-lg overflow-hidden">
          {children}
          <ToastProvider />
        </div>
      </body>
    </html>
  );
}
